
import React, { useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { Button, Input, Card, Table, Th, Td } from '../ui/CyberComponents';
import { Checkbox } from '../ui/checkbox';
import { useAvailableShipments, useCreateManifest } from '../../hooks/useManifests';
import { HUBS } from '../../lib/constants';
import { useNavigate } from 'react-router-dom';
import { ArrowLeft, Truck, Plane, Package, Save } from 'lucide-react';
import { toast } from 'sonner';

const schema = z.object({
    fromHub: z.enum(['IMPHAL', 'NEW_DELHI']),
    toHub: z.enum(['IMPHAL', 'NEW_DELHI']),
    type: z.enum(['AIR', 'TRUCK']),
    vehicleInfo: z.string().min(1, "Vehicle/Flight No is required"),
    driver: z.string().optional(),
}).refine(data => data.fromHub !== data.toHub, {
    message: "Origin and Destination cannot be the same",
    path: ["toHub"]
});

type FormData = z.infer<typeof schema>;

export const CreateManifestForm: React.FC = () => {
    const navigate = useNavigate();
    const createManifest = useCreateManifest();

    // Use centralized hub UUIDs from constants
    const getHubUuid = (hubId: string) => HUBS[hubId as keyof typeof HUBS]?.uuid;

    const { register, watch, handleSubmit, formState: { errors } } = useForm<FormData>({
        resolver: zodResolver(schema),
        defaultValues: {
            fromHub: 'IMPHAL',
            toHub: 'NEW_DELHI',
            type: 'AIR'
        }
    });

    const fromHub = watch('fromHub');
    const toHub = watch('toHub');
    const type = watch('type');

    // Fetch available shipments for this route
    const { data: shipments, isLoading: loadingShipments } = useAvailableShipments(getHubUuid(fromHub) ?? '', getHubUuid(toHub) ?? '');
    const [selectedShipmentIds, setSelectedShipmentIds] = useState<string[]>([]);

    const toggleShipment = (id: string) => {
        setSelectedShipmentIds(prev =>
            prev.includes(id) ? prev.filter(x => x !== id) : [...prev, id]
        );
    };

    const selectAll = (checked: boolean) => {
        if (checked && shipments) {
            setSelectedShipmentIds(shipments.map(s => s.id));
        } else {
            setSelectedShipmentIds([]);
        }
    };

    const onSubmit = async (data: FormData) => {
        if (selectedShipmentIds.length === 0) {
            toast.error("Please select at least one shipment to manifest");
            return;
        }

        try {
            await createManifest.mutateAsync({
                from_hub_id: getHubUuid(data.fromHub) ?? '',
                to_hub_id: getHubUuid(data.toHub) ?? '',
                type: data.type,
                vehicle_meta: {
                    identifier: data.vehicleInfo,
                    driver: data.driver,
                    notes: `Autogenerated`
                },
                shipment_ids: selectedShipmentIds
            });
            navigate('/manifests');
        } catch (e) {
            console.error(e);
            toast.error('Failed to create manifest. Please try again.');
        }
    };

    const totalSelectedWeight = shipments
        ?.filter(s => selectedShipmentIds.includes(s.id))
        .reduce((sum, s) => sum + s.total_weight, 0) || 0;

    return (
        <form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
            <div className="flex items-center gap-4 mb-6">
                <Button variant="ghost" onClick={() => navigate('/manifests')} type="button">
                    <ArrowLeft className="w-5 h-5" />
                </Button>
                <h2 className="text-2xl font-bold bg-gradient-to-r from-cyber-neon to-purple-400 bg-clip-text text-transparent">
                    Create Manifest
                </h2>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                {/* Left: Settings */}
                <Card className="p-6 space-y-4 h-fit border border-cyber-border bg-white dark:bg-cyber-surface">
                    <h3 className="text-sm font-bold text-muted-foreground uppercase">Route Settings</h3>

                    <div className="grid grid-cols-2 gap-4">
                        <div>
                            <label className="text-xs text-muted-foreground mb-1 block">ORIGIN</label>
                            <select {...register('fromHub')} className="w-full bg-muted border border-cyber-border rounded px-3 py-2 text-sm">
                                {Object.values(HUBS).map(h => <option key={h.id} value={h.id}>{h.name}</option>)}
                            </select>
                        </div>
                        <div>
                            <label className="text-xs text-muted-foreground mb-1 block">DESTINATION</label>
                            <select {...register('toHub')} className="w-full bg-muted border border-cyber-border rounded px-3 py-2 text-sm">
                                {Object.values(HUBS).map(h => <option key={h.id} value={h.id}>{h.name}</option>)}
                            </select>
                            {errors.toHub && <span className="text-red-500 text-xs">{errors.toHub.message}</span>}
                        </div>
                    </div>

                    <div>
                        <label className="text-xs text-muted-foreground mb-1 block">TYPE</label>
                        <div className="grid grid-cols-2 gap-3">
                            <label className={`
                                border rounded-lg p-3 flex flex-col items-center cursor-pointer transition-all
                                ${type === 'AIR' ? 'border-primary text-primary bg-primary/5' : 'border-cyber-border opacity-60'}
                            `}>
                                <input type="radio" value="AIR" {...register('type')} className="hidden" />
                                <Plane className="w-5 h-5 mb-1" />
                                <span className="text-xs">AIR</span>
                            </label>
                            <label className={`
                                border rounded-lg p-3 flex flex-col items-center cursor-pointer transition-all
                                ${type === 'TRUCK' ? 'border-purple-500 text-purple-500 bg-purple-500/5' : 'border-cyber-border opacity-60'}
                            `}>
                                <input type="radio" value="TRUCK" {...register('type')} className="hidden" />
                                <Truck className="w-5 h-5 mb-1" />
                                <span className="text-xs">TRUCK</span>
                            </label>
                        </div>
                    </div>

                    <div className="space-y-3">
                        <div>
                            <label className="text-xs text-muted-foreground mb-1 block">{type === 'AIR' ? 'FLIGHT NO' : 'VEHICLE NO'}</label>
                            <Input {...register('vehicleInfo')} placeholder={type === 'AIR' ? 'Eg. 6E 6055' : 'Eg. MN01 AA 1234'} />
                            {errors.vehicleInfo && <span className="text-red-500 text-xs">{errors.vehicleInfo.message}</span>}
                        </div>
                        {type === 'TRUCK' && (
                            <div>
                                <label className="text-xs text-muted-foreground mb-1 block">DRIVER NAME</label>
                                <Input {...register('driver')} placeholder="Driver Name" />
                            </div>
                        )}
                    </div>
                </Card>

                {/* Right: Shipment Selection */}
                <div className="lg:col-span-2 space-y-4">
                    <Card className="p-0 border border-cyber-border overflow-hidden bg-white dark:bg-cyber-surface">
                        <div className="p-4 border-b border-cyber-border flex justify-between items-center bg-muted">
                            <div>
                                <h3 className="font-bold flex items-center gap-2">
                                    <Package className="w-4 h-4 text-primary" />
                                    Available Shipments
                                </h3>
                                <p className="text-xs text-muted-foreground">
                                    {shipments?.length || 0} items waiting at {fromHub}
                                </p>
                            </div>

                            {selectedShipmentIds.length > 0 && (
                                <div className="text-right">
                                    <div className="text-xs text-primary font-mono font-bold">
                                        {selectedShipmentIds.length} SELECTED
                                    </div>
                                    <div className="text-[10px] text-muted-foreground">
                                        {totalSelectedWeight.toFixed(1)} kg Total
                                    </div>
                                </div>
                            )}
                        </div>

                        <div className="max-h-[500px] overflow-y-auto">
                            <Table>
                                <thead>
                                    <tr>
                                        <Th>
                                            <Checkbox
                                                checked={shipments && shipments.length > 0 && selectedShipmentIds.length === shipments.length}
                                                onCheckedChange={(checked) => selectAll((checked as boolean))}
                                            />
                                        </Th>
                                        <Th>AWB</Th>
                                        <Th>PKG</Th>
                                        <Th>WEIGHT</Th>
                                        <Th>SERVICE</Th>
                                        <Th>DATE</Th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {loadingShipments && <tr><Td colSpan={6} className="text-center py-10">Loading...</Td></tr>}

                                    {!loadingShipments && shipments?.length === 0 && (
                                        <tr><Td colSpan={6} className="text-center py-10 text-muted-foreground">No shipments found for this route</Td></tr>
                                    )}

                                    {shipments?.map(s => (
                                        <tr key={s.id} onClick={() => toggleShipment(s.id)} className="cursor-pointer hover:bg-muted">
                                            <Td onClick={e => e.stopPropagation()}>
                                                <Checkbox checked={selectedShipmentIds.includes(s.id)} onCheckedChange={() => toggleShipment(s.id)} />
                                            </Td>
                                            <Td className="font-mono font-bold">{s.awb_number}</Td>
                                            <Td>{s.package_count}</Td>
                                            <Td>{s.total_weight} kg</Td>
                                            <Td>
                                                <span className={`text-[10px] px-2 py-0.5 rounded ${s.service_level === 'EXPRESS' ? 'bg-red-500/10 text-red-500' : 'bg-blue-500/10 text-blue-500'}`}>
                                                    {s.service_level}
                                                </span>
                                            </Td>
                                            <Td className="text-right text-xs text-muted-foreground">
                                                {new Date(s.created_at).toLocaleDateString()}
                                            </Td>
                                        </tr>
                                    ))}
                                </tbody>
                            </Table>
                        </div>
                    </Card>

                    <div className="flex justify-end pt-4">
                        <Button type="submit" size="lg" disabled={createManifest.isPending || selectedShipmentIds.length === 0}>
                            {createManifest.isPending ? 'Processing...' : (
                                <>
                                    <Save className="w-4 h-4 mr-2" />
                                    Generate Manifest ({selectedShipmentIds.length})
                                </>
                            )}
                        </Button>
                    </div>
                </div>
            </div>
        </form>
    );
};
