/**
 * Scanner Context Awareness E2E Tests
 *
 * Tests the global vs local scan handling system to ensure:
 * 1. Global navigation works from dashboard/shipments pages
 * 2. Local handling works in manifest builder (no navigation)
 * 3. Context cleanup restores global navigation
 * 4. Duplicate detection works correctly
 * 5. Rapid scanning is handled properly
 */

import { test, expect } from '@playwright/test';
import path from 'node:path';

const authFile = path.resolve(process.cwd(), '.auth/user.json');

test.describe('Scanner Context Awareness', () => {
  // Use shared auth state generated by auth.setup.ts
  test.skip(!process.env.E2E_TEST_EMAIL, 'Requires auth credentials');
  test.use({ storageState: authFile });

  test('should navigate to shipment from dashboard (global context)', async ({ page }) => {
    // Start from dashboard using authenticated storage state
    await page.goto('/dashboard');
    await expect(page).toHaveURL(/\/dashboard/);

    // Simulate scanner input (hardware wedge style)
    await page.keyboard.type('TAC20260003');
    await page.keyboard.press('Enter');

    // Give GlobalScanListener time to open preview dialog
    const dialog = page.locator('[role="dialog"]');
    await expect(dialog).toBeVisible({ timeout: 5000 });

    // New architecture: preview-first flow with Invoice Preview
    await expect(dialog.locator('text=Invoice Preview')).toBeVisible();
  });

  test('should add to manifest without navigation (manifest context)', async ({ page }) => {
    // Navigate to manifests page (auth state already applied)
    await page.goto('/manifests');
    await expect(page.locator('text=Fleet Manifests')).toBeVisible();

    // Open manifest builder
    await page.click('[data-testid="create-manifest-button"]');

    // Wait for manifest builder dialog header (unique heading element)
    await expect(page.getByRole('heading', { name: 'Create Manifest' })).toBeVisible();

    // Give ScanContext time to register MANIFEST_BUILDER context
    await page.waitForTimeout(500);

    // Simulate scanner input (TAC20260003)
    await page.keyboard.type('TAC20260003');
    await page.keyboard.press('Enter');

    // Wait for scan to process
    await page.waitForTimeout(1000);

    // CRITICAL: Verify we're STILL on manifests page (NOT navigated)
    await expect(page).toHaveURL(/\/manifests$/);

    // Verify: Global preview dialog did NOT open while manifest builder owns context
    await expect(page.locator('text=Invoice Preview')).toHaveCount(0);
    console.log('[Test] ✅ Manifest builder blocked global navigation');
  });

  test('should prevent duplicate adds in manifest', async ({ page }) => {
    // Setup: Open manifest builder so MANIFEST_BUILDER context owns scans
    await page.goto('/manifests');
    await page.click('[data-testid="create-manifest-button"]');
    await expect(page.getByRole('heading', { name: 'Create Manifest' })).toBeVisible();

    await page.waitForTimeout(500);

    // Scan same AWB twice
    await page.keyboard.type('TAC20260003');
    await page.keyboard.press('Enter');
    await page.waitForTimeout(500);

    await page.keyboard.type('TAC20260003');
    await page.keyboard.press('Enter');
    await page.waitForTimeout(500);

    // Verify: Still on manifests page and no global preview dialog opened
    await expect(page).toHaveURL(/\/manifests$/);
    await expect(page.locator('text=Invoice Preview')).toHaveCount(0);
  });

  test('should resume global navigation after closing manifest', async ({ page }) => {
    // Setup: Open manifest builder
    await page.goto('/manifests');
    await page.click('[data-testid="create-manifest-button"]');

    // Verify modal is open via dialog heading (step labels may be visually hidden)
    await expect(page.getByRole('heading', { name: 'Create Manifest' })).toBeVisible();

    // While manifest builder is open, scans should NOT trigger global preview
    await page.keyboard.type('TAC20260003');
    await page.keyboard.press('Enter');
    await page.waitForTimeout(500);
    await expect(page.locator('text=Invoice Preview')).toHaveCount(0);

    // Close the modal
    await page.keyboard.press('Escape');

    // Wait for manifest builder dialog to close and context to reset
    await page.waitForTimeout(800);

    // Verify: Modal is closed, back on manifests list
    await expect(page.getByRole('heading', { name: 'Create Manifest' })).toHaveCount(0);

    await expect(page.locator('text=Fleet Manifests')).toBeVisible();

    // Wait for context to reset
    await page.waitForTimeout(500);

    // Simulate scanner input (should now be handled by global preview router)
    await page.keyboard.type('TAC20260003');
    await page.keyboard.press('Enter');

    // Verify: Global preview dialog opens
    const dialog = page.locator('[role="dialog"]');
    await expect(dialog).toBeVisible({ timeout: 5000 });
    await expect(dialog.locator('text=Invoice Preview')).toBeVisible();
    console.log('[Test] ✅ Global preview resumed after closing manifest');
  });

  test('should handle rapid scans in manifest', async ({ page }) => {
    // Setup: Open manifest builder so context is MANIFEST_BUILDER
    await page.goto('/manifests');
    await page.click('[data-testid="create-manifest-button"]');
    await expect(page.getByRole('heading', { name: 'Create Manifest' })).toBeVisible();

    await page.waitForTimeout(500);

    // Rapid scanning: 3 different AWBs
    const awbs = ['TAC20260001', 'TAC20260002', 'TAC20260003'];

    for (const awb of awbs) {
      await page.keyboard.type(awb);
      await page.keyboard.press('Enter');
      await page.waitForTimeout(200); // Small delay between scans
    }

    // Wait for all scans to process
    await page.waitForTimeout(1000);

    // CRITICAL: Verify we're STILL on manifests page and no global preview dialog is shown
    await expect(page).toHaveURL(/\/manifests$/);
    await expect(page.locator('text=Invoice Preview')).toHaveCount(0);
    console.log('[Test] ✅ Still on manifests page after rapid scanning in manifest context');
  });

  test('should navigate from shipments page (global context)', async ({ page }) => {
    // Navigate to shipments page
    await page.goto('/shipments');
    await expect(page.getByRole('heading', { name: 'Shipments' })).toBeVisible();

    // Wait for page to settle
    await page.waitForTimeout(500);

    // Simulate scanner input
    await page.keyboard.type('TAC20260003');
    await page.keyboard.press('Enter');

    // Verify: Global preview dialog opens from shipments list
    const dialog = page.locator('[role="dialog"]');
    await expect(dialog).toBeVisible({ timeout: 5000 });
    await expect(dialog.locator('text=Invoice Preview')).toBeVisible();
    console.log('[Test] ✅ Global preview from shipments page');
  });

  test('should block navigation on scanning page (scanning context)', async ({ page }) => {
    // Navigate to scanning page
    await page.goto('/scanning');
    // Page header was renamed to "Terminal Scanner" in UI polish pass
    await expect(page.getByText('Terminal Scanner')).toBeVisible();

    // Simulate scanner input
    await page.keyboard.type('TAC20260003');
    await page.keyboard.press('Enter');

    // Wait
    await page.waitForTimeout(1000);

    // Verify: STILL on scanning page (didn't navigate)
    await expect(page).toHaveURL(/\/scanning$/);
    console.log('[Test] ✅ Scanning page blocked global navigation');
  });

  test('should handle scan while modal is closing', async ({ page }) => {
    // Open manifest builder
    await page.goto('/manifests');
    await page.click('[data-testid="create-manifest-button"]');

    // On mobile, the step label text may be visually hidden; rely on dialog heading instead
    await expect(page.getByRole('heading', { name: 'Create Manifest' })).toBeVisible();

    // Start closing the modal
    await page.keyboard.press('Escape');

    // Immediately scan before modal fully closes
    await page.keyboard.type('TAC20260003');
    await page.keyboard.press('Enter');

    // Wait for everything to settle
    await page.waitForTimeout(1500);

    // Verify: Either stayed on manifests OR navigated (depends on timing)
    // Both are acceptable as long as no crash/error occurs
    const url = page.url();
    console.log(`[Test] Final URL: ${url}`);
    expect(url).toMatch(/\/(manifests|tracking)/);
  });
});

test.describe('Scanner Console Logging', () => {
  test.skip(!process.env.E2E_TEST_EMAIL, 'Requires auth credentials');
  test.use({ storageState: authFile });

  test('should log context changes in console', async ({ page }) => {
    const logs: string[] = [];

    // Capture console logs
    page.on('console', (msg) => {
      const text = msg.text();
      if (
        text.includes('ScanContext') ||
        text.includes('GlobalScanListener') ||
        text.includes('[ManifestBuilder]') ||
        text.includes('[Scanning Page]')
      ) {
        logs.push(text);
        console.log(`[Browser Console] ${text}`);
      }
    });

    // Open manifest builder (auth state pre-loaded)
    await page.goto('/manifests');
    await page.click('[data-testid="create-manifest-button"]');
    await page.waitForTimeout(500);

    // Scan
    await page.keyboard.type('TAC20260003');
    await page.keyboard.press('Enter');
    await page.waitForTimeout(500);

    // Close manifest
    await page.keyboard.press('Escape');
    await page.waitForTimeout(500);

    // Verify: Context registration/release was logged
    const hasRegistrationLog = logs.some((log) =>
      log.includes('Registering as active scan context')
    );
    const hasReleaseLog = logs.some(
      (log) => log.includes('Releasing scan context') || log.includes('active context: GLOBAL')
    );

    expect(hasRegistrationLog || hasReleaseLog).toBeTruthy();
    console.log(`[Test] Captured ${logs.length} relevant console logs`);
  });
});
