-- Add description column to tracking_events table
-- Required by close_manifest_atomic, depart_manifest_atomic, arrive_manifest_atomic RPCs
-- which INSERT a human-readable description alongside the event

ALTER TABLE public.tracking_events ADD COLUMN IF NOT EXISTS description TEXT;

COMMENT ON COLUMN public.tracking_events.description IS 'Human-readable event description generated by system operations (e.g. manifest close/depart/arrive)';
